version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:936141@db:5432/hackrx_db
    depends_on:
      - db
    volumes:
      - .:/app

  streamlit:
    build: .
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hackrx_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 936141
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
